graphql-hive/graphql-eslint

.changeset/lucky-eggs-fetch.md, packages/plugin/src/processors/code-files.ts
Added ability to apply fixes in graphql fragments in js,ts etc files.
Really handy feature!
❤️ thanks for the plugin
=> Added `supportsAutofix` to the processor

.changeset/short-beers-lick.md, .changeset/two-bobcats-listen.md, README.md, docs/parser-options.md, packages/plugin/package.json, packages/plugin/src/parser.ts, packages/plugin/src/rules/require-id-when-available.ts, packages/plugin/src/rules/validate-against-schema.ts, packages/plugin/src/schema.ts, packages/plugin/src/sibling-operations.ts, packages/plugin/src/types.ts, packages/plugin/src/utils.ts, packages/plugin/tests/require-id-when-available.spec.ts, yarn.lock
Related: https://github.com/dotansimha/graphql-eslint/issues/25
=> Improve performance for parserServices, and allow access to sibling operations in rules

.changeset/lemon-singers-suffer.md, docs/README.md, docs/rules/no-deprecated.md, packages/plugin/src/rules/index.ts, packages/plugin/src/rules/no-deprecated.ts, packages/plugin/tests/no-deprecated.spec.ts
Related: https://github.com/dotansimha/graphql-eslint/issues/6
=> NEW RULE: `no-deprecated`

.changeset/eleven-crabs-lick.md, packages/plugin/src/schema.ts
Related: https://github.com/dotansimha/graphql-eslint/issues/241
=> Fix issues with loading schemas from code-files

.changeset/forty-llamas-exist.md, docs/rules/no-unreachable-types.md, packages/plugin/src/graphql-ast.ts, packages/plugin/src/parser.ts, packages/plugin/src/rules/no-unreachable-types.ts, packages/plugin/src/types.ts, packages/plugin/src/utils.ts, packages/plugin/tests/no-unreachable-types.spec.ts, patches/eslint+7.16.0.patch
=> NEW RULE: no-unreachable-types rule

docs/README.md, packages/plugin/src/rules/index.ts
related: https://github.com/dotansimha/graphql-eslint/issues/267
=> fix: Definition for rule 'no-unreachable-types' was not found

packages/plugin/tests/no-unreachable-types.spec.ts
test for issue: https://github.com/dotansimha/graphql-eslint/issues/273
=> test: `no-unreachable-types` does not recognize implemented interfaces

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
This PR is in relation to https://github.com/the-guild-org/Stack/pull/9
**NOTE:** You might want to enable the discussions tab in this repo.
- Updated README with Contributing, License and Code of Conduct
- Added Issue and PR Templates
=> Contributing flow - Updated README with CODE OF CONDUCT, License, Contributing, Added PR and Issue templates

.changeset/spotty-lies-hang.md, packages/plugin/src/rules/no-unreachable-types.ts, packages/plugin/tests/no-unreachable-types.spec.ts
=> Pass if type implements reachable interface

packages/plugin/src/rules/graphql-js-validation.ts
Issue: https://github.com/dotansimha/graphql-eslint/issues/408
=> fix: broken links to graphql-js

.github/workflows/main.yml
*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Adding links to sandbox or providing screenshots can help us understand more about this PR and take action on it as appropriate
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- OS:
- …
=> Fixes for ci (drop node 10, added 16)

.changeset/ninety-deers-end.md, docs/rules/lone-schema-definition.md, packages/plugin/src/rules/graphql-js-validation.ts, packages/plugin/tests/lone-schema-definition.spec.ts
test for issue: https://github.com/dotansimha/graphql-eslint/issues/406
=> test for `lone-schema-definition` rule

.changeset/long-apricots-taste.md, packages/plugin/src/rules/graphql-js-validation.ts, packages/plugin/tests/possible-type-extension.spec.ts
Related: https://github.com/dotansimha/graphql-eslint/issues/296#issuecomment-843888975
=> Fixes for graphql-js rules issues

.changeset/mean-lies-invite.md, docs/README.md, docs/rules/no-unused-fields.md, packages/plugin/src/graphql-ast.ts, packages/plugin/src/parser.ts, packages/plugin/src/rules/index.ts, packages/plugin/src/rules/no-unused-fields.ts, packages/plugin/src/types.ts, packages/plugin/src/utils.ts, packages/plugin/tests/no-unused-fields.spec.ts
Report about unused fields based on siblings operations/fragments/inline fragments
Fixes https://github.com/dotansimha/graphql-eslint/issues/9
=> 🎉 New rule `no-unused-fields`

README.md
Based on my comment here: https://github.com/dotansimha/graphql-eslint/issues/359#issuecomment-852339065
The VSCode integration notes are not entirely correct and some information is missing:
- having a GraphQL IDE extension is needed
- `eslint.options` config with `extensions` setting is redundant
After each change in the following tests, I reloaded VSCode.
- I tested with both [GraphQL by GraphQL Foundation](https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql) and [GraphQL by Maxime Quandale](https://marketplace.visualstudio.com/items?itemName=mquandalle.graphql) - having either of them installed worked, having none didn't
- I tried putting and removing the `eslint.options` from `settings.json` config - it made no difference for me.
- tested with or without …
=> Update README on the VSCode integration

.changeset/hot-items-fry.md, docs/README.md, docs/rules/known-fragment-names.md, docs/rules/no-deprecated.md, docs/rules/no-hashtag-description.md, docs/rules/require-id-when-available.md, docs/rules/unique-fragment-name.md, docs/rules/unique-operation-name.md, packages/plugin/src/estree-parser/utils.ts, packages/plugin/src/index.ts, packages/plugin/src/processors/code-files.ts, packages/plugin/src/rules/graphql-js-validation.ts, packages/plugin/src/rules/no-deprecated.ts, packages/plugin/src/rules/no-hashtag-description.ts, packages/plugin/src/rules/require-id-when-available.ts, packages/plugin/src/rules/unique-fragment-name.ts, packages/plugin/src/rules/unique-operation-name.ts, packages/plugin/src/schema.ts, packages/plugin/src/testkit.ts, packages/plugin/src/types.ts, packages/plugin/src/utils.ts, packages/plugin/tests/mocks/unique-fragment.js, packages/plugin/tests/unique-fragment-name.spec.ts, packages/plugin/tests/unique-operation-name.spec.ts, scripts/generate-docs.ts
Related: https://github.com/dotansimha/graphql-eslint/issues/515
=> fix: compare siblings with real filepath instead of virtual in `unique-fragment-name` and `unique-operation-name`

.changeset/real-pigs-develop.md, packages/plugin/src/schema.ts
Fixes #526
You can merge this one first https://github.com/dotansimha/graphql-eslint/pull/532 or close him because this PR already include his commit.
=> Fix schema loading when `graphql-config` is used

.changeset/lemon-donkeys-hammer.md, packages/plugin/src/graphql-ast.ts, packages/plugin/src/graphql-config.ts, packages/plugin/src/parser.ts, packages/plugin/src/sibling-operations.ts, packages/plugin/src/types.ts, packages/plugin/src/utils.ts
Caching for that rules never worked, I fixed this
=> 2️⃣ Fix caching for `no-unreachable-types` and `no-unused-fields` rules

.changeset/weak-keys-fold.md, package.json, packages/plugin/src/graphql-ast.ts, packages/plugin/tests/no-unreachable-types.spec.ts, yarn.lock
Fixes https://github.com/dotansimha/graphql-eslint/issues/571
=> fix `no-unreachable-types` rule when interface implementing other interface

.changeset/two-bees-chew.md, packages/plugin/src/estree-parser/converter.ts, packages/plugin/src/estree-parser/utils.ts, packages/plugin/src/rules/no-hashtag-description.ts, packages/plugin/src/testkit.ts, packages/plugin/src/utils.ts, packages/plugin/tests/no-hashtag-description.spec.ts
Related https://github.com/dotansimha/graphql-eslint/issues/570
=> fix(no-hashtag-description): allow hashtag comments between fields and arguments

.changeset/nasty-pumpkins-taste.md, docs/README.md, docs/rules/match-document-filename.md, packages/plugin/package.json, packages/plugin/src/rules/avoid-operation-name-prefix.ts, packages/plugin/src/rules/avoid-typename-prefix.ts, packages/plugin/src/rules/index.ts, packages/plugin/src/rules/input-name.ts, packages/plugin/src/rules/match-document-filename.ts, packages/plugin/src/rules/naming-convention.ts, packages/plugin/src/rules/no-operation-name-suffix.ts, packages/plugin/src/rules/require-description.ts, packages/plugin/src/rules/selection-set-depth.ts, packages/plugin/src/utils.ts, packages/plugin/tests/match-document-filename.spec.ts, yarn.lock
Related https://github.com/dotansimha/graphql-eslint/pull/458
=> make works `match-document-filename` rule

.changeset/shiny-buttons-relax.md, packages/plugin/src/graphql-ast.ts, packages/plugin/tests/no-unreachable-types.spec.ts
fix https://github.com/dotansimha/graphql-eslint/issues/748
=> fix false positive case in `no-unreachable-types` rule when directive is used on schema

README.md
*Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.*
Enhanced basic configuration instructions in the docs pursuant to @B2o5T's explanation in https://github.com/dotansimha/graphql-eslint/discussions/757
=> Docs: Enhance basic config instructions.

.changeset/short-dolphins-brush.md, examples/basic/package.json, examples/code-file/package.json, examples/graphql-config-code-file/package.json, examples/graphql-config/package.json, examples/prettier/package.json, packages/plugin/package.json, packages/plugin/tests/known-fragment-names.spec.ts, packages/plugin/tests/mocks/user-fields-with-nested-fragment.gql, packages/plugin/tests/mocks/user.graphql, packages/plugin/tests/no-unused-fragments.spec.ts, yarn.lock
related https://github.com/dotansimha/graphql-eslint/issues/654
=> add test for `known-fragment-names` rule with import nested fragments + update `graphql-tools/import` package

.changeset/three-shoes-relax.md, .changeset/twenty-bottles-care.md, docs/rules/naming-convention.md, docs/rules/require-description.md, examples/basic/.eslintrc.js, packages/plugin/src/configs/all.ts, packages/plugin/src/rules/naming-convention.ts, packages/plugin/src/rules/require-description.ts, packages/plugin/src/utils.ts, packages/plugin/tests/__snapshots__/require-description.spec.ts.snap, packages/plugin/tests/require-description.spec.ts
related https://github.com/dotansimha/graphql-eslint/issues/62
=> [breaking change] modify options API for `require-description` rule

.changeset/quick-elephants-punch.md, packages/plugin/package.json
=> fix: exports for react native

.changeset/loud-coins-stare.md, packages/plugin/src/rules/match-document-filename.ts, packages/plugin/src/rules/naming-convention.ts, packages/plugin/src/utils.ts, packages/plugin/tests/match-document-filename.spec.ts, packages/plugin/tests/naming-convention.spec.ts
https://user-images.githubusercontent.com/7361780/145687520-87fd0914-016b-4674-a06b-b6478a3110c6.mov
=> Add suggestions for `naming convention` rule

.changeset/tender-adults-shave.md, .eslintrc.js, docs/rules/require-id-when-available.md, packages/plugin/src/rules/require-id-when-available.ts, packages/plugin/src/rules/selection-set-depth.ts, packages/plugin/tests/__snapshots__/examples.spec.ts.snap, packages/plugin/tests/__snapshots__/require-id-when-available.spec.ts.snap, packages/plugin/tests/parser.spec.ts, packages/plugin/tests/require-id-when-available.spec.ts
related: https://github.com/dotansimha/graphql-eslint/issues/382
=> feat: support multiple id field names in `require-id-when-available` rule

.changeset/old-jeans-push.md, docs/rules/known-fragment-names.md, docs/rules/no-undefined-variables.md, docs/rules/no-unused-variables.md, packages/plugin/package.json, packages/plugin/src/rules/graphql-js-validation.ts, packages/plugin/src/types.ts, packages/plugin/tests/__snapshots__/known-fragment-names.spec.ts.snap, packages/plugin/tests/__snapshots__/no-undefined-variables.spec.ts.snap, packages/plugin/tests/known-fragment-names.spec.ts, packages/plugin/tests/mocks/known-fragment-names.ts, packages/plugin/tests/mocks/known-fragment-names/operation-with-undefined-fragment.gql, packages/plugin/tests/mocks/known-fragment-names/user-fields.gql, packages/plugin/tests/mocks/known-fragment-names/user.gql, packages/plugin/tests/mocks/no-undefined-variables.gql, packages/plugin/tests/mocks/no-unused-variables.gql, packages/plugin/tests/mocks/post.graphql, packages/plugin/tests/mocks/user.graphql, packages/plugin/tests/no-undefined-variables.spec.ts, packages/plugin/tests/no-unused-fragments.spec.ts, packages/plugin/tests/no-unused-variables.spec.ts, yarn.lock
fix https://github.com/dotansimha/graphql-eslint/issues/472
=> feat: remove the need of `#import` comments in favor of `parserOptions.operations`

.changeset/sweet-toys-speak.md, docs/rules/strict-id-in-types.md, packages/plugin/src/rules/strict-id-in-types.ts, packages/plugin/tests/__snapshots__/strict-id-in-types.spec.ts.snap, packages/plugin/tests/strict-id-in-types.spec.ts
fix https://github.com/dotansimha/graphql-eslint/discussions/871
=> fix: ignore root types in `strict-id-in-types` rule

.changeset/dull-geckos-tickle.md, docs/README.md, docs/rules/require-description.md, packages/plugin/src/rules/require-description.ts, packages/plugin/tests/__snapshots__/require-description.spec.ts.snap, packages/plugin/tests/require-description.spec.ts, scripts/generate-docs.ts
fixes https://github.com/dotansimha/graphql-eslint/discussions/907
=> feat: add new option `OperationDefinition` in `require-description` rule

.changeset/fuzzy-chairs-tease.md, packages/plugin/src/rules/require-description.ts, packages/plugin/tests/__snapshots__/examples.spec.ts.snap, packages/plugin/tests/__snapshots__/require-description.spec.ts.snap, packages/plugin/tests/require-description.spec.ts
related https://github.com/dotansimha/graphql-eslint/issues/924
=> chore: clarify report message for `require-description` rule

.changeset/strong-fireants-greet.md, docs/rules/match-document-filename.md, packages/plugin/src/rules/match-document-filename.ts, packages/plugin/tests/match-document-filename.spec.ts
related https://github.com/dotansimha/graphql-eslint/issues/919
=> feat: add new style `matchDocumentStyle` for `match-document-filename` rule

.changeset/beige-bats-happen.md, docs/rules/alphabetize.md, examples/basic/package.json, examples/code-file/package.json, examples/graphql-config-code-file/package.json, examples/graphql-config/package.json, examples/prettier/package.json, packages/plugin/src/estree-parser/estree-ast.ts, packages/plugin/src/rules/alphabetize.ts, packages/plugin/src/rules/description-style.ts, packages/plugin/src/rules/graphql-js-validation.ts, packages/plugin/src/rules/no-anonymous-operations.ts, packages/plugin/src/rules/no-root-type.ts, packages/plugin/src/rules/require-description.ts, packages/plugin/src/rules/require-id-when-available.ts, packages/plugin/src/testkit.ts, packages/plugin/src/types.ts, packages/plugin/src/utils.ts, packages/plugin/tests/__snapshots__/alphabetize.spec.ts.snap, packages/plugin/tests/__snapshots__/description-style.spec.ts.snap, packages/plugin/tests/alphabetize.spec.ts, packages/plugin/tests/no-unused-fields.spec.ts, packages/plugin/tests/require-id-when-available.spec.ts, patches/eslint+8.9.0.patch, scripts/match-eslint.mjs, yarn.lock
Fixes https://github.com/B2o5T/graphql-eslint/discussions/935#discussioncomment-2195091
=> feat: add `definitions` option for `alphabetize` rule

.changeset/tall-kids-compete.md, packages/plugin/src/rules/alphabetize.ts, packages/plugin/tests/__snapshots__/alphabetize.spec.md, packages/plugin/tests/alphabetize.spec.ts
fixes https://github.com/B2o5T/graphql-eslint/issues/978
=> fix autofix sort for variables in `alphabetize` rule

.changeset/neat-apes-doubt.md, .github/workflows/tests.yml, packages/plugin/src/rules/graphql-js-validation.ts, packages/plugin/tests/known-fragment-names.spec.ts, scripts/match-graphql.mjs
fixes https://github.com/B2o5T/graphql-eslint/issues/976 https://github.com/B2o5T/graphql-eslint/issues/983
=> [known-fragment-names]: fix when fragment used on interface and union

.changeset/tricky-pans-know.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/PULL_REQUEST_TEMPLATE.md, .github/labels.yml, .github/workflows/canary.yml, .github/workflows/github.yml, .github/workflows/release.yml, .github/workflows/tests.yml, package.json, packages/plugin/package.json, scripts/canary-release.ts, yarn.lock
fixes https://github.com/B2o5T/graphql-eslint/issues/996
=> feat: update `graphql-config` to fix loading schema via url

.changeset/seven-dogs-press.md, docs/custom-rules.md, docs/rules/relay-page-info.md, examples/code-file/.eslintrc.js, examples/code-file/not-query.js, packages/plugin/package.json, packages/plugin/src/processor.ts, packages/plugin/src/rules/relay-page-info.ts, packages/plugin/tests/__snapshots__/examples.spec.md, packages/plugin/tests/examples.spec.ts, yarn.lock
fixes https://github.com/B2o5T/graphql-eslint/issues/1021
=> fix: processor should always return code string in preprocess method

README.md, examples/prettier/.eslintrc.cjs, examples/prettier/package.json, yarn.lock
=> chore: upgrade eslint-plugin-prettier to 4.1.0

README.md
_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Adding links to sandbox or providing screenshots can help us understand more about this PR and take action on it as appropriate
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- OS:
- …
=> docs: typo and dead link

.changeset/four-trains-glow.md, packages/plugin/src/rules/selection-set-depth.ts, packages/plugin/tests/__snapshots__/selection-set-depth.spec.md, packages/plugin/tests/selection-set-depth.spec.ts
fixes https://github.com/B2o5T/graphql-eslint/issues/1090
=> fix(selection-set-depth): fix `TypeError` when suggestion tried to apply to fragment that located in different file

.changeset/perfect-pugs-carry.md, packages/plugin/src/rules/alphabetize.ts, packages/plugin/tests/__snapshots__/alphabetize.spec.md, packages/plugin/tests/alphabetize.spec.ts
fixes https://github.com/B2o5T/graphql-eslint/issues/1113
=> fix(alphabetize): should not fail when selection is aliased

.github/workflows/tests.yml, package.json
_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Adding links to sandbox or providing screenshots can help us understand more about this PR and take action on it as appropriate
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- OS:
- …
=> ci: use shared actions

.changeset/odd-zebras-search.md, .eslintrc.cjs, package.json, packages/plugin/src/rules/graphql-js-validation.ts, packages/plugin/src/rules/selection-set-depth.ts, packages/plugin/src/types.ts, patches/eslint-plugin-eslint-plugin+5.0.6.patch, yarn.lock
fixes https://github.com/B2o5T/graphql-eslint/issues/1146
=> improve `RuleDocsInfo` type, set `description` and `url` as required fields

.changeset/nice-drinks-sin.md, packages/plugin/src/processor.ts, packages/plugin/src/types.ts
fixes https://github.com/B2o5T/graphql-eslint/issues/1143#issuecomment-1257615181
=> fix race condition of loading `graphql-config`

.changeset/fair-donkeys-heal.md, docs/README.md, docs/rules/require-type-pattern-with-oneof.md, packages/plugin/src/configs/schema-all.ts, packages/plugin/src/rules/index.ts, packages/plugin/src/rules/require-nullable-fields-with-oneof.ts, packages/plugin/src/rules/require-type-pattern-with-oneof.ts, packages/plugin/tests/__snapshots__/require-type-pattern-with-oneof.spec.md, packages/plugin/tests/require-type-pattern-with-oneof.spec.ts
fixes https://github.com/B2o5T/graphql-eslint/issues/1137
=> add new rule `require-type-pattern-with-oneof`

.changeset/@graphql-eslint_eslint-plugin-1344-dependencies.md, .changeset/heavy-pots-kiss.md, docs/README.md, docs/rules/lone-executable-definition.md, docs/rules/require-nullable-fields-with-oneof.md, packages/plugin/package.json, packages/plugin/src/configs/base.ts, packages/plugin/src/configs/index.ts, packages/plugin/src/configs/operations-all.ts, packages/plugin/src/configs/operations-recommended.ts, packages/plugin/src/configs/relay.ts, packages/plugin/src/configs/schema-all.ts, packages/plugin/src/configs/schema-recommended.ts, packages/plugin/src/rules/lone-executable-definition.ts, packages/plugin/src/rules/require-nullable-fields-with-oneof.ts, pnpm-lock.yaml, scripts/generate-configs.ts, scripts/postbuild.ts
fixes https://github.com/B2o5T/graphql-eslint/issues/1343 https://github.com/B2o5T/graphql-eslint/issues/1341
=> fix ESLint couldn't find the config "./configs/base", add `tslib` to dependencies

README.md
_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of
the pull request._
Fixes broken README links to packages/plugin/src & to examples/monorepo. 
Please include a summary of the change and which issue is fixed. Please also include relevant
motivation and context. List any dependencies that are required for this change.
Fixes #1356 
- By clicking the new links and verifying they work
[CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/maste …
=> docs(readme): fix broken README links

.eslintrc.cjs, .gitignore, package.json, packages/plugin/src/estree-converter/utils.ts, packages/plugin/src/rules/alphabetize.ts, packages/plugin/src/rules/no-hashtag-description.ts, packages/plugin/src/rules/require-description.ts, pnpm-lock.yaml, tsconfig.eslint.json, website/next-sitemap.config.cjs, website/package.json, website/src/components/graphql-editor.tsx, website/src/components/play-page.tsx, website/src/components/select.tsx
_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of
the pull request._
Please include a summary of the change and which issue is fixed. Please also include relevant
motivation and context. List any dependencies that are required for this change.
expected)
Adding links to sandbox or providing screenshots can help us understand more about this PR and take
action on it as appropriate
- OS:
- …
=> Website fixes

website/theme.config.tsx
_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of
the pull request._
Please include a summary of the change and which issue is fixed. Please also include relevant
motivation and context. List any dependencies that are required for this change.
expected)
Adding links to sandbox or providing screenshots can help us understand more about this PR and take
action on it as appropriate
- OS:
- …
=> try `twitter:image` tag

.github/workflows/release.yml, .github/workflows/website-integrity.yml, .github/workflows/website.yml
Add Algolia integrity check for PRs, and publish on every release.
@B2o5T please make sure to remove all ALGOLIA-related secrets, except `ALGOLIA_ADMIN_API_KEY` - and make sure that this one does exist :)
=> setup Algolia

.changeset/neat-cows-worry.md, packages/plugin/src/rules/require-selections/index.test.ts, packages/plugin/src/rules/require-selections/index.ts, packages/plugin/src/rules/require-selections/snapshot.md
fixes https://github.com/dimaMachina/graphql-eslint/issues/1737
=> Reenable running `require-id-when-available` on `FragmentDefinition`

.changeset/config.json, .github/FUNDING.yml, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, examples/code-file/package.json, examples/graphql-config/package.json, examples/prettier/package.json, examples/programmatic/package.json, package.json, packages/plugin/package.json, pnpm-lock.yaml, scripts/generate-docs.ts, website/content/docs/configs.mdx, website/content/docs/custom-rules.mdx, website/content/rules/prettier.md
fixes https://github.com/dimaMachina/graphql-eslint/issues/2341
=> fix bug report repo example link

.changeset/pretty-moons-happen.md, packages/plugin/src/rules/require-description/index.ts
fixes https://github.com/dimaMachina/graphql-eslint/issues/2774
=> fix error `TypeError: Cannot read properties of undefined (reading 'type')` in `require-description` rule

.changeset/@graphql-eslint_eslint-plugin-2783-dependencies.md, .changeset/spotty-vans-protect.md, packages/plugin/package.json, packages/rule-tester/src/index.ts
fixes https://github.com/dimaMachina/graphql-eslint/issues/2441
=> add `json-schema-to-ts` as optional peer dependency

.changeset/clever-nails-wash.md, packages/plugin/package.json, pnpm-lock.yaml
See https://github.com/dimaMachina/graphql-eslint/discussions/2803#discussioncomment-11448217.
expected)
=> fix(deps): increase minimum graphql-config version

website/app/layout.tsx
Updated the link to go to Hive blog.
=> Link to Hive blog
