.changeset/bright-clocks-relate.md, packages/plugin/src/parser.ts
In v14, there is no `Lexer` class exported.
=> Fix compatibility with GraphQL v14

.changeset/eighty-maps-juggle.md, .changeset/serious-games-yawn.md, docs/rules/validate-against-schema.md, packages/plugin/src/estree-parser/converter.ts, packages/plugin/src/rules/validate-against-schema.ts, packages/plugin/tests/validate-against-schema.spec.ts
Related: https://github.com/dotansimha/graphql-eslint/issues/66
=> Fixes for rawNode and validation rule

packages/plugin/src/rules/require-id-when-available.ts, packages/plugin/tests/require-id-when-available.spec.ts
With a schema like
```graphql
type Query {
vehicles: [Vehicle!]!
}
interface Vehicle {
id: ID!
}
type Car implements Vehicle {
id: ID!
mileage: Int
}
```
and a query like
```graphql
query { 
vehicles { 
id 
...on Car { 
mileage 
} 
} 
}
```
I currently get a lint error because it'll say that `id` should also be present in the Car selection set.
This PR attempts to fix this issue. I had a problem with the types on `node.parent` which is why I typed it as `any`. Not quite sure what I should type it as to get it to work.
=> [require-id-when-available] fix for inline fragments on interfaces

.changeset/wise-paws-speak.md, packages/plugin/src/rules/input-name.ts, packages/plugin/tests/input-name.spec.ts
Related https://github.com/dotansimha/graphql-eslint/issues/75, which we also ran into.
This PR updates the `input-name` rule so it will ignore any fields that aren't on the `Mutation` type. This assumes that the schema is using the default `Mutation` type name. If we want to support a custom mutation type name we could add it as an option or alternatively parse for the `schema { mutation: MyMutationRootType }`
Thanks!
=> input-name: Ignore non-Mutation fields.

docs/rules/require-description.md
When trying a a copy/paste I noticed a missing `]` this rule configuration. Thanks!
=> docs: fix syntax on require-description example

.changeset/shaggy-planets-travel.md, packages/plugin/src/processors/code-files.ts
This is PR aims to extends compatibility of this plugin with eslint ecosystem
Related #88 
This proposal comes from https://github.com/dotansimha/graphql-eslint/issues/88#issuecomment-722531443 @lavigneer's comment.
The workaround plays with relative path in the block filename containing original source text. It allows other plugins to resolve original source file on the filesystem.
=> Fix processor compatibility with other plugins

.changeset/tame-onions-wink.md, examples/graphql-config-code-file/.eslintrc.json, examples/graphql-config-code-file/graphql.config.yml, examples/graphql-config-code-file/package.json, examples/graphql-config-code-file/query.js, examples/graphql-config-code-file/schema.graphql, packages/plugin/src/parser.ts, packages/plugin/src/schema.ts, packages/plugin/src/sibling-operations.ts
This PR aims to unify the loaders available when using eslint config and `graphql-config`.
Related #232
Today, `graphql-eslint` is loading schema and operations via `graphql-config` if available and not disable. Otherwise, it uses directly `graphql-tools` and `parserOptions` of eslint configuration file.
When parsing schema and operations directly via `graphql-tools`, we use some loaders such as `CodeFileLoader` which allow to parse graphql inside JavaScript and TypeScript files.
But when we use `graphql-config`, this loaders are not used by default.
This lead to projects not lintable if used with graphql-config.
My proposition is to create a custom extension for `graphql-config` which allows us to add the same loaders than when we directly use `graphql-tools`.
We don't have to mind if …
=> Add code file loader when using graphql-config

.changeset/curvy-cameras-fetch.md, .changeset/sweet-colts-jam.md, docs/README.md, docs/rules/no-hashtag-description.md, packages/plugin/src/estree-parser/converter.ts, packages/plugin/src/rules/index.ts, packages/plugin/src/rules/no-hashtag-description.ts, packages/plugin/tests/no-hashtag-description.spec.ts
Related: https://github.com/dotansimha/graphql-eslint/issues/65
=> NEW RULE: no-hashtag-description

.changeset/cool-frogs-kiss.md, packages/plugin/src/graphql-config.ts, packages/plugin/src/parser.ts, packages/plugin/src/schema.ts, packages/plugin/src/sibling-operations.ts
This PR aims to cache `graphql-config` object to avoid loading configuration for each linted file.
Related #233 
For now, we are loading the graphql configuration file in the parser, which is called by eslint for each linted file.
Since the configuration should not change between the parsing of to files, we shouldn't reload it each time. It is a performance optimization but also a matters of coherence during execution. With a lot of files, there is a timming where we can change the configuration file during eslint parsing phase. Which will lead to have some file linted with old grpahql config, some other with the new one. 
My proposition is to globally cache the graphql config object for the entire execution.
I have moved out graphql-config logic to its own file which allow me to have a …
=> Add cache for graphql-config loading

.changeset/fuzzy-mice-return.md, docs/rules/naming-convention.md, docs/rules/require-description.md, docs/rules/require-id-when-available.md, packages/plugin/src/rules/naming-convention.ts, packages/plugin/tests/naming-convention.spec.ts, scripts/generate-docs.ts
To make this rule more flexible, it needs to be able to take an object as well as format style string. For example, we might want to check whether a field has a certain suffix. More details: https://github.com/dotansimha/graphql-eslint/issues/195
The config is normalized into an object before passing into the validation function.
Note that we can no longer rely on the default enum check because it also tries to validate that an object is part of the enum. Therefore, the validation function needs to check the format enums now.
Also, added a suffix option. The targeted property must have the correct suffix or it will error.
=> [naming-convention] Update property schema to accept objects. Add prefix and suffix option

.changeset/swift-hairs-jam.md, packages/plugin/src/rules/naming-convention.ts, packages/plugin/tests/naming-convention.spec.ts
Related: https://github.com/dotansimha/graphql-eslint/issues/175
=> fix(naming-convention): fix issues with numeric values

docs/README.md
@dotansimha sorry, missed the `rules` path in: https://github.com/dotansimha/graphql-eslint/pull/268. also removed the `md` extension in the link.
`unreachable types` works great now btw 🙌  but there seems to be a bug with (certain/or all) `interfaces` not being recognized as being used: https://github.com/dotansimha/graphql-eslint/issues/273
I'll try to create a repro and/or a PR.
=> doc: fix readme

.changeset/early-turkeys-admire.md, packages/plugin/src/rules/input-name.ts, packages/plugin/tests/input-name.spec.ts
Add caseSensitiveInputType, checkMutations, checkQueries options to input-name rule
caseSensitiveInputType: When false the input type name must be <mutationName>Input but is not case sensitive.
checkMutations (default true): Apply this rule to mutations.
checkQueries (default false): Apply this rule to queries.
Setup default option values, previously all defaulting to undefined.
Also fixed documentation error which says that `checkInputType` defaults to `true`, when infact it defaults to `false`.
Addressed https://github.com/dotansimha/graphql-eslint/issues/276
=> Add options to input-name rule. Addresses #276

.changeset/funny-swans-speak.md, docs/rules/naming-convention.md, packages/plugin/src/rules/naming-convention.ts, packages/plugin/tests/naming-convention.spec.ts
This PR implements the following:
- `QueryDefinition` option: This can be used specifically to target queries. As a result, the `FieldDefinition` option no longer targets queries which could be a breaking change
- `forbiddenPrefixes` property: used to report if any definition has one of the declared prefixes
- `forbiddenSuffixes` property: used to report if any definition has one of the declared suffixes
Other minor change(s):
- `checkNode` now takes full `property` object to make future properties easier to implement
- Fix wrong node type for UnionDefinition [here](https://github.com/dotansimha/graphql-eslint/pull/256/files#diff-9afe7600c3e6002f30eb08d02a06c30afda813baa781871f4b9c7af93039f2d6R345). Was `Scalar`, now `Union`
Related: https://github.com/dotansimha/graphql-eslint/issues/253
=> [naming-convention]  Add QueryDefinition option, forbiddenSuffixes and forbiddenPrefixes properties.

.changeset/empty-donuts-destroy.md, packages/plugin/src/processors/code-files.ts
Related #88
ESLint supports `text` directly, no need to use the hacky way. See https://github.com/eslint/eslint/blob/master/lib/linter/linter.js#L1298
Besides, I've fixed related `eslint-plugin-prettier`'s issue at https://github.com/prettier/eslint-plugin-prettier/pull/401
=> fix: original file should not be considered as file block

docs/rules/avoid-operation-name-prefix.md, docs/rules/description-style.md, docs/rules/input-name.md, docs/rules/naming-convention.md, docs/rules/require-description.md, docs/rules/selection-set-depth.md, docs/rules/strict-id-in-types.md, scripts/generate-docs.ts
Issue: https://github.com/dotansimha/graphql-eslint/issues/410
The mistake is that ESLint RuleTester accept options as array https://github.com/eslint/eslint/blob/master/lib/rule-tester/rule-tester.js#L497 but in eslintrc config we must provide options as object
after review you can close this pr #329 as i fixed generated docs code ;)
=> Fix generated documentation for certain rules

.changeset/ninety-colts-switch.md, .husky/_/husky.sh, packages/plugin/src/rules/naming-convention.ts, packages/plugin/tests/naming-convention.spec.ts
- Make naming-convention rule able to handle OperationDefinition.
- This feature was already in the [document](https://github.com/dotansimha/graphql-eslint/blob/master/docs/rules/naming-convention.md#operationdefinition), but it doesn't work.
- Also, I added a simple test for this change.
Fixes #380
=> Support OperationDefinition naming convention

.changeset/stupid-glasses-kneel.md, packages/plugin/src/rules/selection-set-depth.ts
=> Fix console.warn typo in `selection-set-depth` rule

.changeset/fuzzy-dolphins-attack.md, packages/plugin/src/rules/naming-convention.ts, packages/plugin/tests/naming-convention.spec.ts
Related https://github.com/dotansimha/graphql-eslint/issues/435
=> fix: allow anonymous operations for `naming-convention` rule

.changeset/tall-keys-divide.md, packages/plugin/src/rules/unique-fragment-name.ts, packages/plugin/src/rules/unique-operation-name.ts, packages/plugin/src/utils.ts
Related: https://github.com/dotansimha/graphql-eslint/issues/296#issuecomment-843950972
=> Fix issues with Windows paths

.changeset/dry-vans-smile.md, docs/rules/known-fragment-names.md, packages/plugin/src/parser.ts, packages/plugin/src/rules/graphql-js-validation.ts, packages/plugin/src/sibling-operations.ts, packages/plugin/tests/known-fragment-names.spec.ts, packages/plugin/tests/mocks/user-fields.graphql, packages/plugin/tests/mocks/user.graphql
Finally I made it work. Any feedback is welcome
Fixes https://github.com/dotansimha/graphql-eslint/issues/385
=> 🎉 New feature: Support `#import` for `known-fragment-names` rule

.changeset/six-pianos-eat.md, packages/plugin/src/parser.ts, packages/plugin/src/rules/graphql-js-validation.ts, packages/plugin/tests/eslint-directives.spec.ts, packages/plugin/tests/mocks/test-directives-with-import.graphql
Fixes https://github.com/dotansimha/graphql-eslint/issues/504
=> 1️⃣ fix: make working ESLint directive in files that contains import comments

.changeset/witty-beans-turn.md, docs/rules/no-unused-fragments.md, packages/plugin/package.json, packages/plugin/src/rules/graphql-js-validation.ts, packages/plugin/src/rules/unique-fragment-name.ts, packages/plugin/src/sibling-operations.ts, packages/plugin/tests/known-fragment-names.spec.ts, packages/plugin/tests/mocks/post-fields.graphql, packages/plugin/tests/mocks/post.graphql, packages/plugin/tests/mocks/user-schema.graphql, packages/plugin/tests/no-unused-fragments.spec.ts, packages/plugin/tests/unique-fragment-name.spec.ts, yarn.lock
Fixes https://github.com/dotansimha/graphql-eslint/issues/507
Fixes https://github.com/dotansimha/graphql-eslint/issues/281
=> 2️⃣ Fix `unique-fragment-name` and `no-unused-fragments` rules, skip graphql `#import` comments for siblings

.changeset/proud-bikes-tease.md, packages/plugin/src/sibling-operations.ts
Fixes https://github.com/dotansimha/graphql-eslint/issues/517
=> fix: documents in graphql-config can be null

.changeset/wild-rules-guess.md, package.json, packages/plugin/src/graphql-config.ts, packages/plugin/src/schema.ts, packages/plugin/src/sibling-operations.ts, packages/plugin/src/types.ts, packages/plugin/tests/mocks/graphql-server.ts, packages/plugin/tests/mocks/unique-fragment.js, packages/plugin/tests/schema.spec.ts, tsconfig.json
Related https://github.com/dotansimha/graphql-eslint/issues/525
To fix error we need to update `url-loader` to alpha version
=> 3️⃣ Test schema loaders, fix `Expected signal to be an instanceof AbortSignal` error when `UrlLoader` is used

.changeset/four-coats-vanish.md, packages/plugin/src/rules/unique-fragment-name.ts, packages/plugin/src/sibling-operations.ts, packages/plugin/tests/mocks/two-fragments-in-code-file.js, packages/plugin/tests/unique-fragment-name.spec.ts, packages/plugin/tests/unique-operation-name.spec.ts
Related https://github.com/dotansimha/graphql-eslint/issues/515
`@graphql-tools/graphql-tag-pluck` v7 returns multiple extracted documents instead of single like in v6 so I updated `@graphql-tools` dependencies to v7 and I added support for virtual filepath for siblings
=> 4️⃣ fix false negative case in unique-fragment-name rule

.changeset/great-beans-design.md, packages/plugin/src/graphql-ast.ts, packages/plugin/src/rules/no-unreachable-types.ts, packages/plugin/src/sibling-operations.ts, packages/plugin/tests/mocks/graphql-server.ts, packages/plugin/tests/no-unreachable-types.spec.ts
Currently, there are 6 false-negative cases, is this is by design?
I think the `type`, `interface`, `scalar`, `union` or `directive` must be marked as unreachable if he is not used by some other type at less once
```gql
type Query {
node(id: ID!): User
}
interface User implements Node {
id: ID!
name: String
}
interface Node {
id: ID!
}
interface Missing { # currently we assert that `Type "Missing" is unreachable` 
mid: ID!
}
type SuperUser implements User & Node { # but this type is also unreachable
id: ID!
name: String
isSuper: Boolean!
}
```
The next tests marked as valid but they are invalid
```gql
interface User {
id: String
}
type SuperUser implements User { # type must be marked as unreachable
id: String
}
extend type SuperUser { # extend type must be marked as unreachable because …
```
=> fix false negative cases for `no-unreachable-types` rule

.changeset/strong-mails-rest.md, packages/plugin/package.json, packages/plugin/src/graphql-ast.ts, packages/plugin/src/schema.ts, packages/plugin/src/sibling-operations.ts, packages/plugin/src/utils.ts, patches/eslint+7.32.0.patch, yarn.lock
This PR also adds `loaderCache` that removes the need of `schemaCache` and `operationsCache` but I didn't remove it in this PR because it seems to need more changes than removing them.
=> enhance(eslint-plugin): refactor the parts using tools

.changeset/metal-squids-listen.md, packages/plugin/package.json
related https://github.com/dotansimha/graphql-eslint/issues/292#issuecomment-962125460
Currently, when trying to use @graphql-eslint on yarn berry there is an error, because `@babel/code-frame` is declared in `devDependencies` (we use `@babel/code-frame` only in `GraphQLRuleTester` but we export him also)
```sh
Oops! Something went wrong! :(
ESLint: 7.32.0
Error: Cannot read config file: /Users/dimitri/Desktop/graphql-eslint-issue-repro/.eslintrc.js
Error: @graphql-eslint/eslint-plugin tried to access @babel/code-frame, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
Required package: @babel/code-frame
Required by: @graphql-eslint/eslint-plugin@virtual:28a64deb451814b2a4d09c4e73b83102a09eb40705b3643f110dd175c81a0b4d602ca2762a0264adf93e4bb998c7a …
```
=> fix: make works graphql-eslint in yarn berry

.changeset/unlucky-buses-eat.md, packages/plugin/src/rules/no-scalar-result-type-on-mutation.ts, packages/plugin/tests/__snapshots__/no-scalar-result-type-on-mutation.spec.ts.snap, packages/plugin/tests/no-scalar-result-type-on-mutation.spec.ts
fix https://github.com/dotansimha/graphql-eslint/issues/796
=> fix: ignore arguments in `no-scalar-result-type-on-mutation` rule

.changeset/young-roses-invite.md, packages/plugin/src/rules/no-hashtag-description.ts, packages/plugin/tests/no-hashtag-description.spec.ts
related https://github.com/dotansimha/graphql-eslint/issues/817
=> fix: ignore operations and fragments in `no-hashtag-description` rule

.changeset/cold-vans-help.md, packages/plugin/src/rules/graphql-js-validation.ts, packages/plugin/tests/__snapshots__/executable-definitions.spec.ts.snap, packages/plugin/tests/__snapshots__/fields-on-correct-type.spec.ts.snap, packages/plugin/tests/__snapshots__/lone-schema-definition.spec.ts.snap, packages/plugin/tests/__snapshots__/possible-type-extension.spec.ts.snap, packages/plugin/tests/__snapshots__/unique-type-names.spec.ts.snap, packages/plugin/tests/fields-on-correct-type.spec.ts
fix https://github.com/dotansimha/graphql-eslint/issues/825
@dotansimha you can explore snapshots to see that now we'll have a correct error report location for `graphql-js` rules 😀.
=> fix error report location for `graphql-js` rules

.changeset/shy-mangos-grin.md, docs/rules/require-id-when-available.md, packages/plugin/src/rules/require-id-when-available.ts, packages/plugin/tests/__snapshots__/require-id-when-available.spec.ts.snap, packages/plugin/tests/require-id-when-available.spec.ts
fix https://github.com/dotansimha/graphql-eslint/issues/731
I think it's reasonable we need to check selections only in operations but not in fragment definition
also, I ignore selections where the parent kind is OperationDefinition node as it's redundant check
=> Ignore fragment definition in require id when available rule

.changeset/relative-graphqlrc.md, packages/plugin/src/graphql-config.ts, packages/plugin/tests/mocks/using-config/.graphqlrc, packages/plugin/tests/mocks/using-config/schema-in-config.graphql, packages/plugin/tests/mocks/using-config/test.graphql, packages/plugin/tests/schema.spec.ts
Before this change, `loadConfigSync` from graphql-config would use `process.cwd` to find any .graphqlrc files.
With a project like this:
```
project/
- packages/
- app/
- schema.graphql
- .eslintrc
- .graphqlrc
- documents/
- operation.graphql
```
the VSCode Eslint plugin throws an error about not being able to find the schema.graphql file when linting the operation.graphql.
This change passes in the [`rootDir` option](https://graphql-config.com/load-config#rootdir) to `loadConfigSync` using the directory of the linted file. This will allow the .graphqlrc file to live in subfolders of the open project.
Fixes #899
https://stackblitz.com/edit/node-6fhvcm?file=README.md
Unit tests, but I also installed my local copy in a separate project using `"file:"` in package.json to verify that it …
=> fix: find graphqlrc files relative to linted file

.changeset/neat-eagles-tap.md, .changeset/nice-pandas-confess.md, packages/plugin/src/rules/require-id-when-available.ts, packages/plugin/src/rules/selection-set-depth.ts, packages/plugin/src/sibling-operations.ts, packages/plugin/src/types.ts, packages/plugin/tests/__snapshots__/examples.spec.md, packages/plugin/tests/__snapshots__/require-id-when-available.spec.md, packages/plugin/tests/require-id-when-available.spec.ts
fixes https://github.com/B2o5T/graphql-eslint/issues/964
=> `require-id-when-available` check nested selections in fragments

.changeset/early-cooks-taste.md, packages/plugin/src/rules/naming-convention.ts, packages/plugin/tests/naming-convention.spec.ts
fixes https://github.com/B2o5T/graphql-eslint/issues/1007
=> fix: allow single letter for snake_case and UPPER_CASE in `naming-convention` rule

.changeset/dirty-rules-sin.md, docs/rules/require-id-when-available.md, packages/plugin/src/rules/require-id-when-available.ts, packages/plugin/tests/require-id-when-available.spec.ts
Selecting the `id` field with an alias should also be valid as discussed in #1017 .
Fixes #1017 
I've added a test. Do we need more tests?
I'm not sure if I should bump the version etc. Should I do that? Or will you perform the changes required for a new release?
=> Support aliases in require-id-when-available

.changeset/young-stingrays-invite.md, packages/plugin/src/rules/graphql-js-validation.ts, packages/plugin/tests/known-directives.spec.ts
fixes https://github.com/B2o5T/graphql-eslint/issues/1076
=> fix(known-directives): support `ignoreClientDirectives` for `OperationDefinition`

.changeset/nasty-dancers-act.md, packages/plugin/src/testkit.ts
This is just a small TS type tweak to add a missing property to `GraphQLInvalidTestCase`.
If you create your own rule with a `fix` available, eslint throws the following error if the `output` is missing:
```
Message:
The rule fixed the code. Please add 'output' property.
```
One can add the `output` property to the test case, but the package is missing the type support
```
ruleTester.runGraphQLTests('my-rule', rule, {
valid: [
{
code: /* GraphQL */ `
type Book {
_authorAge: Int! @tag(name: "experimental")
}
`,
},
],
invalid: [
{
code: /* GraphQL */ `
type Book {
_authorAge: Int!
}
`,
errors: [
{
message: "The @tag directive is missing.",
},
],
output: /* GraphQL */ `
type Book {
_authorAge: Int! @tag(name: "experimental")
}
`,
},
],
})
```
I copied over the type declaration from …
=> Missing output property in GraphQLInvalidTestCase

.changeset/tough-apes-deny.md, .github/workflows/release.yml, .github/workflows/tests.yml, packages/plugin/src/types.ts
fixes https://github.com/B2o5T/graphql-eslint/issues/1146
=> make `RuleDocsInfo` type optional

.changeset/wet-ads-rush.md, .github/renovate.json, packages/plugin/package.json, packages/plugin/src/cache.ts, packages/plugin/src/documents.ts, packages/plugin/src/parser.ts, packages/plugin/src/rules/no-unused-fields.ts, packages/plugin/src/rules/selection-set-depth.ts, packages/plugin/src/rules/unique-fragment-name.ts, packages/plugin/src/schema.ts, packages/plugin/src/types.ts, packages/plugin/src/utils.ts, packages/plugin/tests/schema.spec.ts
fixes https://github.com/B2o5T/graphql-eslint/issues/593
=> feat: reload schema/documents cache (only for **current project**) in VSCode

.changeset/healthy-readers-study.md, package.json, packages/plugin/src/cache.ts, pnpm-lock.yaml
fixes https://github.com/B2o5T/graphql-eslint/issues/1246
=> fix increased memory usage for ESLint CLI

docs/README.md, docs/rules/lone-anonymous-operation.md, packages/plugin/src/rules/graphql-js-validation.ts
*Note: I deliberately ignored the PR description template, because this is a documentation-only change, and the template is not fitting here.*
The previous wording in the `lone-anonymous-operation` rule docs was difficult to understand. I simplified and clarified it.
=> Simplify wording in rule docs

docs/README.md, scripts/generate-docs.ts
This is a documentation-only change.
When looking through the list of rules, it's good to see at a glance which rules apply to schema documents and which apply to operations.
This PR adds another column with icons for both.
=> Add category icons to rule list in docs

docs/custom-rules.md
Again a documentation-only change. [astexplorer.net](https://astexplorer.net/#/gist/e72aaccc1e57cbba41659d73cabbf75c/f10ee29317a31ff8012a21762a382c4a03c34d40) helped me find the correct node attributes for implementing my rule in #1316.
=> Link to astexplorer.net from custom rules docs

.changeset/good-baboons-bathe.md, .changeset/strange-donuts-warn.md, .gitignore, .husky/_/husky.sh, docs/README.md, docs/rules/lone-executable-definition.md, docs/rules/require-description.md, packages/plugin/src/configs/operations-all.json, packages/plugin/src/rules/index.ts, packages/plugin/src/rules/lone-executable-definition.ts, packages/plugin/src/rules/require-description.ts, packages/plugin/src/utils.ts, packages/plugin/tests/__snapshots__/lone-executable-definition.spec.md, packages/plugin/tests/lone-executable-definition.spec.ts, packages/plugin/tests/no-unreachable-types.spec.ts, packages/plugin/tests/possible-type-extension.spec.ts, packages/plugin/tests/require-field-of-type-query-in-mutation-result.spec.ts, scripts/generate-docs.ts
Adds the suggested rule from #1311 to require one file per query/fragment/mutation/subscription. Fixes #1311.
I've created new unit tests for the rule, and also ran `npm test` to be sure that I did not break anything.
- OS: Ubuntu 22.04
- NodeJS: 16.18.0
The latest commit (b0b0cc802ea5d66da3d1939416df81b08284d6d2) were automatically generated with `npm run prettier`. I'm happy to revert it if required.
=> Create new lone-executable-definition rule

packages/plugin/src/rules/lone-executable-definition.ts
Follow-up to #1316 and #1319. This is a small refactoring to avoid repeating the same GraphQL definition types in the `type` and the schema definition.
=> DRY in `lone-executable-definition` rule

.changeset/early-geckos-search.md, docs/README.md, docs/rules/require-nullable-fields-with-oneof.md, package.json, packages/plugin/src/configs/schema-all.ts, packages/plugin/src/rules/index.ts, packages/plugin/src/rules/require-nullable-fields-with-oneof.ts, packages/plugin/tests/__snapshots__/require-nullable-fields-with-oneof.spec.md, packages/plugin/tests/require-nullable-fields-with-oneof.spec.ts, pnpm-lock.yaml, scripts/create-rule.ts
fixes https://github.com/B2o5T/graphql-eslint/issues/1138
=> add new rule `require-nullable-fields-with-oneof`

.changeset/two-avocados-grab.md, docs/README.md, docs/rules/no-one-place-fragments.md, packages/plugin/src/configs/operations-all.ts, packages/plugin/src/rules/index.ts, packages/plugin/src/rules/no-one-place-fragments.ts, packages/plugin/tests/__snapshots__/no-one-place-fragments.spec.md, packages/plugin/tests/mocks/no-one-place-fragments.graphql, packages/plugin/tests/no-one-place-fragments.spec.ts
fixes https://github.com/B2o5T/graphql-eslint/issues/72
> find fragments and variables that used only in one place and suggest to inline them.
=> add new rule `no-one-place-fragments`

.changeset/@graphql-eslint_eslint-plugin-1338-dependencies.md, .changeset/three-moose-roll.md, examples/multiple-projects-graphql-config/package.json, packages/plugin/package.json, pnpm-lock.yaml
fixes https://github.com/B2o5T/graphql-eslint/issues/1180
=> update `graphql-config` to v4.4.0 that no longer requires `typescript` to be installed

.changeset/breezy-walls-invent.md, .vscode/launch.json, .vscode/settings.json, examples/vue-code-file/test.vue, packages/plugin/src/processor.ts, packages/plugin/tests/__snapshots__/examples.spec.md
fixes https://github.com/B2o5T/graphql-eslint/issues/480#issuecomment-1279962333
=> report errors on first character for `*.vue`/`*.svelte` code, due graphql-tag-pluck limitation we can't know right location

.changeset/thin-chicken-doubt.md, packages/plugin/src/types.ts
_Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request._
Type issue fix for `RuleDocsInfo`
Fixes # (1146)
Adding links to sandbox or providing screenshots can help us understand more about this PR and take action on it as appropriate
- TS Build errors relating to `description` field is gone (when `strict` flag is turned on)
- No new TS Build errors
- OS: MacOS Monterey
- `@graphql-eslint/.3.11.2`:
- NodeJS: 16.16
=> Fixed type issue for RuleDocsInfo

.changeset/config.json, .changeset/early-poems-reflect.md, package.json, packages/plugin/src/estree-converter/converter.ts, packages/plugin/src/parser.ts, packages/plugin/src/schema.ts, packages/plugin/src/types.ts, packages/plugin/src/utils.ts, packages/plugin/tests/schema.spec.ts, pnpm-lock.yaml, website/theme.config.tsx
related https://github.com/B2o5T/graphql-eslint/pull/1385
=> Another solution: do not crash ESLint when schema/siblings contains validation errors

.changeset/honest-yaks-trade.md, packages/plugin/src/rules/no-unreachable-types.ts, packages/plugin/tests/no-unreachable-types.spec.ts
fixes https://github.com/B2o5T/graphql-eslint/issues/301
=> fix `no-unreachable-types` ignore types from directive arguments with request locations

.changeset/green-vans-leave.md, packages/plugin/src/rules/naming-convention.ts, packages/plugin/tests/__snapshots__/naming-convention.spec.md, packages/plugin/tests/naming-convention.spec.ts
https://github.com/B2o5T/graphql-eslint/issues/1521
This adds two new configuration options to `naming-convention`:
* `requiredPrefixes` – if supplied, the selected field name must have one of the supplied prefixes
* `requiredSuffixes` – if supplied, the selected field name must have one of the supplied suffixes
Fixes #[1521](https://github.com/B2o5T/graphql-eslint/issues/1521)
expected)
Adding links to sandbox or providing screenshots can help us understand more about this PR and take
action on it as appropriate
[CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master …
=> Add `requiredPrefixes` and `requiredSuffixes` to `naming-convention`

.changeset/lovely-otters-watch.md, package.json, packages/plugin/src/rules/require-nullable-result-in-root.ts, packages/plugin/tests/__snapshots__/require-nullable-result-in-root.spec.md, packages/plugin/tests/require-nullable-result-in-root.spec.ts, pnpm-lock.yaml
fixes https://github.com/B2o5T/graphql-eslint/issues/1663
=> fix `TypeError: Cannot read properties of undefined (reading 'kind')` for `require-nullable-result-in-root` rule

.changeset/spicy-books-tell.md, packages/plugin/src/rules/require-import-fragment.ts, packages/plugin/src/rules/require-nullable-result-in-root.ts, scripts/create-rule.ts
This fixes the two rule suggestions, which result in a 404 when you try to click the links in vscode.
- require-import-fragment
- require-nullable-result-in-root
Fixes #1715 
expected)
- OS: MaOS / vscode
- NodeJS: v19.9.0
=> Fix broken suggestion URLs in rules

.changeset/grumpy-tips-call.md, packages/plugin/src/parser.ts
fixes https://github.com/B2o5T/graphql-eslint/issues/1721
=> fix `Parsing error: Cannot read properties of undefined (reading '0') eslint` in VSCode

.changeset/real-coins-share.md, packages/plugin/src/types.ts
We use some custom eslint plugins that build on top of `@graphql-eslint/eslint-plugin` and it cannot be imported directly from the package if Typescript's config is set to use `moduleResolution: NodeNext` or any other resolution type. This means explicitly making it public is the easiest way to use it.
Fixes #2399
expected)
N/A
No, it is just exposing new type.
N/A
Unfortunately, I'm not able to make tests pass locally. I get this failure:
```
@graphql-eslint/eslint-plugin:test:  FAIL  __tests__/examples.spec.ts > Examples > should work in monorepo
@graphql-eslint/eslint-plugin:test: Error: …
```
=> exposes GraphQLESTreeNode type

.changeset/breezy-seals-sparkle.md, examples/multiple-projects-graphql-config/query.second-project.js, examples/multiple-projects-graphql-config/schema.second-project.graphql, packages/plugin/__tests__/__snapshots__/examples.spec.md, packages/plugin/src/cache.ts, packages/plugin/src/documents.ts, packages/plugin/src/rules/no-unreachable-types.ts, packages/plugin/src/rules/no-unused-fields.ts, packages/plugin/src/schema.ts
fixes https://github.com/dimaMachina/graphql-eslint/issues/2260#issuecomment-2070092469
=> fix caching issues for `no-unreachable-types` / `no-unused-fields` rules for multi projects

.changeset/lovely-laws-hide.md, .prettierrc.cjs, examples/code-file/eslint.config.js, examples/code-file/package.json, examples/graphql-config/eslint.config.js, examples/graphql-config/package.json, examples/monorepo/eslint.config.js, examples/monorepo/package.json, examples/multiple-projects-graphql-config/package.json, examples/prettier/eslint.config.js, examples/prettier/package.json, examples/programmatic/eslint.config.js, examples/programmatic/package.json, examples/svelte-code-file/package.json, examples/vue-code-file/package.json, package.json, packages/plugin/__tests__/examples.spec.ts, packages/plugin/__tests__/rules.spec.ts, packages/plugin/src/flat-configs.ts, packages/plugin/src/index.browser.ts, packages/plugin/src/index.ts, packages/plugin/src/meta.ts, packages/plugin/src/parser.ts, packages/plugin/src/processor.ts, packages/plugin/tsconfig.json, packages/plugin/tsup.config.ts, pnpm-lock.yaml, website/next.config.js, website/src/components/graphql-editor.tsx, website/src/components/play-page.tsx
fixes https://github.com/dimaMachina/graphql-eslint/issues/2178 https://github.com/dimaMachina/graphql-eslint/issues/2311
=> add `meta` object with `name` and `version` to `parser` and `processor` to be compatible with ESLint 9

.changeset/healthy-moose-kneel.md, packages/plugin/__tests__/examples.spec.ts, packages/plugin/src/meta.ts, packages/plugin/tsup.config.ts
The import attribute syntax (`with { type: "json" }`) is still experimental so warnings showed up when using the library as it was being used to import the package.json file to extract the package version
As an alternative, the current version will be injected on build time through tsup configuration.
Fixes #2614 
Adding links to sandbox or providing screenshots can help us understand more about this PR and take
action on it as appropriate
Test suite passes
- OS: Linux
- `@graphql-eslint/plugins`: 4.0.0-alpha.5
- NodeJS: 18
=> Stop using experimental syntax to load package version

.changeset/yellow-elephants-study.md, packages/plugin/src/rules/no-deprecated/index.test.ts, packages/plugin/src/rules/no-deprecated/index.ts, packages/plugin/src/rules/no-deprecated/snapshot.md, packages/plugin/src/utils.ts, website/src/pages/docs/usage.mdx
fixes https://github.com/dimaMachina/graphql-eslint/issues/2145
=> check for deprecated arguments and object field nodes in graphql operations in `no-deprecated` rule

.changeset/popular-radios-sleep.md, packages/plugin/src/rules/no-unreachable-types/index.test.ts, packages/plugin/src/rules/no-unreachable-types/index.ts
fixes https://github.com/dimaMachina/graphql-eslint/issues/1937
=> fix `no-unreachable-types` to consider wrapped request directive argument types

.changeset/fast-fishes-shake.md, .changeset/popular-ads-help.md, examples/multiple-projects-graphql-config/graphql.config.ts, packages/plugin/src/configs/index.ts, packages/plugin/src/configs/operations-all.ts, packages/plugin/src/configs/operations-recommended.ts, packages/plugin/src/configs/schema-all.ts, packages/plugin/src/configs/schema-recommended.ts, packages/plugin/src/configs/schema-relay.ts, packages/plugin/src/index.ts, packages/plugin/src/rules/index.ts, packages/plugin/tsup.config.ts, scripts/generate-configs.ts, website/app/play/page.client.tsx
fixes https://github.com/dimaMachina/graphql-eslint/issues/2442
=> fix - Config types don't satisfy FlatConfig.Config

.changeset/tame-tigers-own.md, packages/plugin/CHANGELOG.md, packages/plugin/src/rules/selection-set-depth/index.ts, packages/plugin/src/utils.ts, website/content/docs/usage/index.mdx
fixes https://github.com/dimaMachina/graphql-eslint/issues/2312
=> fix https://bit.ly/graphql-eslint-operations links

.changeset/happy-bottles-warn.md, .changeset/long-chicken-press.md, packages/plugin/src/rules/naming-convention/index.test.ts, packages/plugin/src/rules/naming-convention/index.ts, packages/plugin/src/rules/naming-convention/snapshot.md, packages/plugin/src/rules/no-unused-fields/index.ts, packages/plugin/src/rules/require-description/index.test.ts, packages/plugin/src/rules/require-description/index.ts, packages/plugin/src/rules/require-description/snapshot.md, packages/plugin/src/utils.ts, packages/rule-tester/src/index.ts, website/content/docs/index.mdx, website/content/docs/usage/index.mdx, website/content/rules/naming-convention.mdx, website/content/rules/no-unused-fields.mdx, website/content/rules/require-description.mdx, website/tailwind.config.ts
fixes https://github.com/dimaMachina/graphql-eslint/issues/2515
=> add new option `ignoredSelectors` for `require-description` rule, to ignore eslint selectors, e.g. types which ends with `Connection` or `Edge`

.changeset/spotty-lobsters-enjoy.md, packages/plugin/src/rules/naming-convention/index.test.ts, packages/plugin/src/rules/naming-convention/index.ts
fixes https://github.com/dimaMachina/graphql-eslint/issues/1719
=> `allowLeadingUnderscore` and `allowTrailingUnderscore` should not conflict with `ignorePattern` in `naming-convention` rule

.changeset/@graphql-eslint_eslint-plugin-2814-dependencies.md, .changeset/fluffy-bottles-switch.md, packages/plugin/__tests__/federation.spec.ts, packages/plugin/package.json, packages/plugin/src/schema.ts, packages/plugin/tsup.config.ts, pnpm-lock.yaml
This PR adds support of parsing federation subgraphs' schema without parsing errors
fixes https://github.com/dimaMachina/graphql-eslint/issues/2812
=> lint federation subgraphs schemas without parse errors

pnpm-lock.yaml, website/app/layout.tsx, website/mdx-components.tsx, website/package.json, website/tailwind.config.ts
Currently, the Documentation link in the navmenu is going to wrong documentation. Adding `developerMenu` in layout explicitly fixes it.
I made the `developerMenu` prop required in next major of `@theguild/components` to avoid errors like this.
There's still an issue of the <kbd>Sign in</kbd> button being present, and it was decided the libraries will just link to /docs there (it's fixed in `@theguild/components` main branch), so we'll have to bump the version when the Tailwind build issue is fixed.
- OS:
- NodeJS:
=> Link to proper /docs and remove Hive-specific links
